version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "data:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 12G
      MAX_PLAYERS: 500
      VIEW_DISTANCE: 15
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      TYPE: FORGE
      FORGEVERSION: xxxxxx
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  data:
  rcon:
